[package]
name = "clevis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
saphyr = "0.0.6"
tempfile = "3.24.0"
toml = "0.9.10"
